import { useEffect, useState } from "react";
import { services } from "../../services";
import type { ManagedAdminUser } from "../../types";

export function UserManagementView({ areas }: { areas: string[] }) {
  const [users, setUsers] = useState<ManagedAdminUser[]>([]); const [error, setError] = useState(""); const [loading, setLoading] = useState(true);
  useEffect(() => { services.admin.listUsers().then(setUsers).catch(() => setError("No fue posible cargar el directorio municipal.")).finally(() => setLoading(false)); }, []);
  async function create(form: HTMLFormElement) { const data = new FormData(form); try { const user = await services.admin.createUser({ email: String(data.get("email")), password: String(data.get("password")), name: String(data.get("name")), areas: String(data.get("areas")).split(",").map((area) => area.trim()).filter(Boolean), accessLevel: String(data.get("accessLevel")) as "operator" | "coordinator" }); setUsers((current) => [...current, user]); form.reset(); } catch { setError("No fue posible crear la cuenta. Verifica los datos."); } }
  return <section className="admin-view"><header className="view-heading"><div><p className="eyebrow">Coordinación</p><h2>Equipo y accesos</h2><p>Gestiona las cuentas que pueden atender reportes de tus áreas.</p></div></header>{error && <div className="error-banner">{error}</div>}<form className="admin-form" onSubmit={(event) => { event.preventDefault(); void create(event.currentTarget); }}><label>Nombre<input name="name" required /></label><label>Correo<input name="email" type="email" required /></label><label>Contraseña inicial<input name="password" type="password" minLength={8} required /></label><label>Áreas (separadas por coma)<input name="areas" defaultValue={areas[0] || ""} required /></label><label>Nivel<select name="accessLevel"><option value="operator">Operador</option><option value="coordinator">Coordinador</option></select></label><button className="primary-button">Crear cuenta</button></form>{loading ? <p>Cargando directorio…</p> : <div className="report-list">{users.map((user) => <article className="report-row" key={user.uid}><div className="report-row-top"><strong>{user.name}</strong><span>{user.active ? "Activa" : "Inactiva"}</span></div><p>{user.email} · {user.accessLevel === "coordinator" ? "Coordinación" : "Operador"}</p><small>{user.areas?.join(", ")}</small><button className="text-button" onClick={() => void services.admin.setUserActive(user.uid, !user.active).then((next) => setUsers((current) => current.map((item) => item.uid === next.uid ? next : item)))}> {user.active ? "Desactivar" : "Activar"}</button></article>)}</div>}</section>;
}
